/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package puzzle;

import javax.swing.JOptionPane;

/**
 *
 * @author JuanCaCha
 */
public class VistaPuzzle extends javax.swing.JFrame {

    ModeloPuzzle a = new ModeloPuzzle();
    int array[] = new int[15];
    int cont = 0;
    public VistaPuzzle() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Juego Puzzle");
        b16.setVisible(false);
        desorganizar();
        
        
    }
    private boolean completado (){
        if (b1.getText().equals("1")&&b2.getText().equals("2")&&b3.getText().equals("3")&&
            b4.getText().equals("4")&&b5.getText().equals("5")&&b6.getText().equals("6")&&
            b7.getText().equals("7")&&b8.getText().equals("8")&&b9.getText().equals("9")&&
            b10.getText().equals("10")&&b11.getText().equals("11")&&b12.getText().equals("12")&&
            b13.getText().equals("13")&&b14.getText().equals("14")&&b15.getText().equals("15")) {
                return true;
        }
        return false;
    }
    private void desorganizar(){
        array=a.Numaleatorios(15);
        b1.setText(Integer.toString(array[0]));
        b2.setText(Integer.toString(array[1]));
        b3.setText(Integer.toString(array[2]));
        b4.setText(Integer.toString(array[3]));
        b5.setText(Integer.toString(array[4]));
        b6.setText(Integer.toString(array[5]));
        b7.setText(Integer.toString(array[6]));
        b8.setText(Integer.toString(array[7]));
        b9.setText(Integer.toString(array[8]));
        b10.setText(Integer.toString(array[9]));
        b11.setText(Integer.toString(array[10]));
        b12.setText(Integer.toString(array[11]));
        b13.setText(Integer.toString(array[12]));
        b14.setText(Integer.toString(array[13]));
        b15.setText(Integer.toString(array[14]));
        cont = 0;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Mov = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        b5 = new javax.swing.JButton();
        b6 = new javax.swing.JButton();
        b7 = new javax.swing.JButton();
        b8 = new javax.swing.JButton();
        b9 = new javax.swing.JButton();
        b10 = new javax.swing.JButton();
        b11 = new javax.swing.JButton();
        b12 = new javax.swing.JButton();
        b13 = new javax.swing.JButton();
        b14 = new javax.swing.JButton();
        b15 = new javax.swing.JButton();
        b16 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Castellar", 0, 18)); // NOI18N
        jLabel1.setText("PUZZLE");

        jLabel2.setText("Movimientos: ");

        Mov.setText("0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Mov, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(470, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Mov))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel2.setPreferredSize(new java.awt.Dimension(400, 400));
        jPanel2.setLayout(new java.awt.GridLayout(4, 4));

        b1.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        b1.setText("1");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        jPanel2.add(b1);

        b2.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        b2.setText("2");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        jPanel2.add(b2);

        b3.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        b3.setText("3");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        jPanel2.add(b3);

        b4.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        b4.setText("4");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        jPanel2.add(b4);

        b5.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        b5.setText("5");
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });
        jPanel2.add(b5);

        b6.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        b6.setText("6");
        b6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b6ActionPerformed(evt);
            }
        });
        jPanel2.add(b6);

        b7.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        b7.setText("7");
        b7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b7ActionPerformed(evt);
            }
        });
        jPanel2.add(b7);

        b8.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        b8.setText("8");
        b8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b8ActionPerformed(evt);
            }
        });
        jPanel2.add(b8);

        b9.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        b9.setText("9");
        b9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b9ActionPerformed(evt);
            }
        });
        jPanel2.add(b9);

        b10.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        b10.setText("10");
        b10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b10ActionPerformed(evt);
            }
        });
        jPanel2.add(b10);

        b11.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        b11.setText("11");
        b11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b11ActionPerformed(evt);
            }
        });
        jPanel2.add(b11);

        b12.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        b12.setText("12");
        b12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b12ActionPerformed(evt);
            }
        });
        jPanel2.add(b12);

        b13.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        b13.setText("13");
        b13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b13ActionPerformed(evt);
            }
        });
        jPanel2.add(b13);

        b14.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        b14.setText("14");
        b14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b14ActionPerformed(evt);
            }
        });
        jPanel2.add(b14);

        b15.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        b15.setText("15");
        b15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b15ActionPerformed(evt);
            }
        });
        jPanel2.add(b15);

        b16.setFont(new java.awt.Font("Dialog", 0, 48)); // NOI18N
        b16.setText("16");
        b16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b16ActionPerformed(evt);
            }
        });
        jPanel2.add(b16);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 435, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
       if (b1.isVisible() == false) {
                b1.setText(b2.getText());
                b1.setVisible(true);
                b2.setVisible(false);
                cont++;
                Mov.setText(Integer.toString(cont));
        }if (b6.isVisible() == false) {
                b6.setText(b2.getText());
                b6.setVisible(true);
                b2.setVisible(false);
                cont++;
                Mov.setText(Integer.toString(cont));
        }if (b3.isVisible() == false) {
                b3.setText(b2.getText());
                b3.setVisible(true);
                b2.setVisible(false);
                cont++;
                Mov.setText(Integer.toString(cont));
        }
        if (completado()) {
                JOptionPane.showMessageDialog(null, "Puzzle Completado");
                desorganizar();
                
        }
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        if (b2.isVisible() == false) {
                b2.setText(b3.getText());
                b2.setVisible(true);
                b3.setVisible(false);
                cont++;
                Mov.setText(Integer.toString(cont));
        }if (b4.isVisible() == false) {
                b4.setText(b3.getText());
                b4.setVisible(true);
                b3.setVisible(false);
                cont++;
                Mov.setText(Integer.toString(cont));
        }if (b7.isVisible() == false) {
                b7.setText(b3.getText());
                b7.setVisible(true);
                b3.setVisible(false);
                cont++;
                Mov.setText(Integer.toString(cont));
        }if (completado()) {
                JOptionPane.showMessageDialog(null, "Puzzle Completado");  
                desorganizar();
        }
    }//GEN-LAST:event_b3ActionPerformed

    private void b9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b9ActionPerformed
        if (b5.isVisible() == false) {
                b5.setText(b9.getText());
                b5.setVisible(true);
                b9.setVisible(false);
                cont++;
                Mov.setText(Integer.toString(cont));
        }if (b10.isVisible() == false) {
                b10.setText(b9.getText());
                b10.setVisible(true);
                b9.setVisible(false);
                cont++;
                Mov.setText(Integer.toString(cont));
        }if (b13.isVisible() == false) {
                b13.setText(b9.getText());
                b13.setVisible(true);
                b9.setVisible(false);
                cont++;
                Mov.setText(Integer.toString(cont));
        }if (completado()) {
                JOptionPane.showMessageDialog(null, "Puzzle Completado");
                desorganizar();
        }
    }//GEN-LAST:event_b9ActionPerformed

    private void b6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b6ActionPerformed
        if (b5.isVisible() == false) {
                b5.setText(b6.getText());
                b5.setVisible(true);
                b6.setVisible(false);
                cont++;
                Mov.setText(Integer.toString(cont));
        }if (b7.isVisible() == false) {
                b7.setText(b6.getText());
                b7.setVisible(true);
                b6.setVisible(false);
                cont++;
                Mov.setText(Integer.toString(cont));
        }if (b2.isVisible() == false) {
                b2.setText(b6.getText());
                b2.setVisible(true);
                b6.setVisible(false);
                cont++;
                Mov.setText(Integer.toString(cont));
        }if (b10.isVisible() == false) {
                b10.setText(b6.getText());
                b10.setVisible(true);
                b6.setVisible(false);
                cont++;
                Mov.setText(Integer.toString(cont));
        }if (completado()) {
                JOptionPane.showMessageDialog(null, "Puzzle Completado");   
                desorganizar();
        }
    }//GEN-LAST:event_b6ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        if (b2.isVisible() == false) {
                b2.setText(b1.getText());
                b2.setVisible(true);
                b1.setVisible(false);
                cont++;
                Mov.setText(Integer.toString(cont));
        }if (b5.isVisible() == false) {
                b5.setText(b1.getText());
                b5.setVisible(true);
                b1.setVisible(false);
                cont++;
                Mov.setText(Integer.toString(cont));
        }if (completado()) {
                JOptionPane.showMessageDialog(null, "Puzzle Completado"); 
                desorganizar();
        }
    }//GEN-LAST:event_b1ActionPerformed

    private void b7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b7ActionPerformed
        if (b6.isVisible() == false) {
                b6.setText(b7.getText());
                b6.setVisible(true);
                b7.setVisible(false);
                cont++;
                Mov.setText(Integer.toString(cont));
        }if (b8.isVisible() == false) {
                b8.setText(b7.getText());
                b8.setVisible(true);
                b7.setVisible(false);
                cont++;
                Mov.setText(Integer.toString(cont));
        }if (b3.isVisible() == false) {
                b3.setText(b7.getText());
                b3.setVisible(true);
                b7.setVisible(false);
                cont++;
                Mov.setText(Integer.toString(cont));
        }if (b11.isVisible() == false) {
                b11.setText(b7.getText());
                b11.setVisible(true);
                b7.setVisible(false);
                cont++;
                Mov.setText(Integer.toString(cont));
        }if (completado()) {
                JOptionPane.showMessageDialog(null, "Puzzle Completado"); 
                desorganizar();
        }
    }//GEN-LAST:event_b7ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        if (b3.isVisible() == false) {
                b3.setText(b4.getText());
                b3.setVisible(true);
                b4.setVisible(false);
                cont++;
                Mov.setText(Integer.toString(cont));
        }if (b8.isVisible() == false) {
                b8.setText(b4.getText());
                b8.setVisible(true);
                b4.setVisible(false);
                cont++;
                Mov.setText(Integer.toString(cont));
        }if (completado()) {
                JOptionPane.showMessageDialog(null, "Puzzle Completado"); 
                desorganizar();
        }
    }//GEN-LAST:event_b4ActionPerformed

    private void b8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b8ActionPerformed
        if (b4.isVisible() == false) {
                b4.setText(b8.getText());
                b4.setVisible(true);
                b8.setVisible(false);
                cont++;
                Mov.setText(Integer.toString(cont));
        }if (b7.isVisible() == false) {
                b7.setText(b8.getText());
                b7.setVisible(true);
                b8.setVisible(false);
                cont++;
                Mov.setText(Integer.toString(cont));
        }if (b12.isVisible() == false) {
                b12.setText(b8.getText());
                b12.setVisible(true);
                b8.setVisible(false);
                cont++;
                Mov.setText(Integer.toString(cont));
        }if (completado()) {
                JOptionPane.showMessageDialog(null, "Puzzle Completado");    
                desorganizar();
        }
    }//GEN-LAST:event_b8ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
        if (b1.isVisible() == false) {
                b1.setText(b5.getText());
                b1.setVisible(true);
                b5.setVisible(false);
                cont++;
                Mov.setText(Integer.toString(cont));
        }if (b6.isVisible() == false) {
                b6.setText(b5.getText());
                b6.setVisible(true);
                b5.setVisible(false);
                cont++;
                Mov.setText(Integer.toString(cont));
        }if (b9.isVisible() == false) {
                b9.setText(b5.getText());
                b9.setVisible(true);
                b5.setVisible(false);
                cont++;
                Mov.setText(Integer.toString(cont));
        }if (completado()) {
                JOptionPane.showMessageDialog(null, "Puzzle Completado"); 
                desorganizar();
        }
    }//GEN-LAST:event_b5ActionPerformed

    private void b16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b16ActionPerformed
        if (b12.isVisible() == false) {
                b12.setText(b16.getText());
                b12.setVisible(true);
                b16.setVisible(false);
                cont++;
                Mov.setText(Integer.toString(cont));
        }if (b15.isVisible() == false) {
                b15.setText(b16.getText());
                b15.setVisible(true);
                b16.setVisible(false);
                cont++;
                Mov.setText(Integer.toString(cont));
        }if (completado()) {
                JOptionPane.showMessageDialog(null, "Puzzle Completado");    
                desorganizar();
        }
    }//GEN-LAST:event_b16ActionPerformed

    private void b13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b13ActionPerformed
        if (b9.isVisible() == false) {
                b9.setText(b13.getText());
                b9.setVisible(true);
                b13.setVisible(false);
                cont++;
                Mov.setText(Integer.toString(cont));
        }if (b14.isVisible() == false) {
                b14.setText(b13.getText());
                b14.setVisible(true);
                b13.setVisible(false);
                cont++;
                Mov.setText(Integer.toString(cont));
        }if (completado()) {
                JOptionPane.showMessageDialog(null, "Puzzle Completado"); 
                desorganizar();
        
        }    }//GEN-LAST:event_b13ActionPerformed

    private void b14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b14ActionPerformed
        if (b13.isVisible() == false) {
                b13.setText(b14.getText());
                b13.setVisible(true);
                b14.setVisible(false);
                cont++;
                Mov.setText(Integer.toString(cont));
        }if (b15.isVisible() == false) {
                b15.setText(b14.getText());
                b15.setVisible(true);
                b14.setVisible(false);
                cont++;
                Mov.setText(Integer.toString(cont));
        }if (b10.isVisible() == false) {
                b10.setText(b14.getText());
                b10.setVisible(true);
                b14.setVisible(false);
                cont++;
                Mov.setText(Integer.toString(cont));
        }if (completado()) {
                JOptionPane.showMessageDialog(null, "Puzzle Completado");  
                desorganizar();
        }
    }//GEN-LAST:event_b14ActionPerformed

    private void b15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b15ActionPerformed
        if (b14.isVisible() == false) {
                b14.setText(b15.getText());
                b14.setVisible(true);
                b15.setVisible(false);
                cont++;
                Mov.setText(Integer.toString(cont));
        }if (b16.isVisible() == false) {
                b16.setText(b15.getText());
                b16.setVisible(true);
                b15.setVisible(false);
                cont++;
                Mov.setText(Integer.toString(cont));
        }if (b11.isVisible() == false) {
                b11.setText(b15.getText());
                b11.setVisible(true);
                b15.setVisible(false);
                cont++;
                Mov.setText(Integer.toString(cont));
        }if (completado()) {
                JOptionPane.showMessageDialog(null, "Puzzle Completado");   
                desorganizar();
        }
    }//GEN-LAST:event_b15ActionPerformed

    private void b12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b12ActionPerformed
        if (b8.isVisible() == false) {
                b8.setText(b12.getText());
                b8.setVisible(true);
                b12.setVisible(false);
                cont++;
                Mov.setText(Integer.toString(cont));
        }if (b16.isVisible() == false) {
                b16.setText(b12.getText());
                b16.setVisible(true);
                b12.setVisible(false);
                cont++;
                Mov.setText(Integer.toString(cont));
        }if (b11.isVisible() == false) {
                b11.setText(b12.getText());
                b11.setVisible(true);
                b12.setVisible(false);
                cont++;
                Mov.setText(Integer.toString(cont));
        }if (completado()) {
                JOptionPane.showMessageDialog(null, "Puzzle Completado");   
                desorganizar();
        }
    }//GEN-LAST:event_b12ActionPerformed

    private void b10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b10ActionPerformed
        if (b11.isVisible() == false) {
                b11.setText(b10.getText());
                b11.setVisible(true);
                b10.setVisible(false);
                cont++;
                Mov.setText(Integer.toString(cont));
        }if (b6.isVisible() == false) {
                b6.setText(b10.getText());
                b6.setVisible(true);
                b10.setVisible(false);
                cont++;
                Mov.setText(Integer.toString(cont));
        }if (b9.isVisible() == false) {
                b9.setText(b10.getText());
                b9.setVisible(true);
                b10.setVisible(false);
                cont++;
                Mov.setText(Integer.toString(cont));
        }if (b14.isVisible() == false) {
                b14.setText(b10.getText());
                b14.setVisible(true);
                b10.setVisible(false);
                cont++;
                Mov.setText(Integer.toString(cont));
        }if (completado()) {
                JOptionPane.showMessageDialog(null, "Puzzle Completado");  
                desorganizar();
        }
    }//GEN-LAST:event_b10ActionPerformed

    private void b11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b11ActionPerformed
        if (b7.isVisible() == false) {
                b7.setText(b11.getText());
                b7.setVisible(true);
                b11.setVisible(false);
                cont++;
                Mov.setText(Integer.toString(cont));
        }if (b10.isVisible() == false) {
                b10.setText(b11.getText());
                b10.setVisible(true);
                b11.setVisible(false);
                cont++;
                Mov.setText(Integer.toString(cont));
        }if (b12.isVisible() == false) {
                b12.setText(b11.getText());
                b12.setVisible(true);
                b11.setVisible(false);
                cont++;
                Mov.setText(Integer.toString(cont));
        }if (b15.isVisible() == false) {
                b15.setText(b11.getText());
                b15.setVisible(true);
                b11.setVisible(false);
                cont++;
                Mov.setText(Integer.toString(cont));
        }if (completado()) {
                JOptionPane.showMessageDialog(null, "Puzzle Completado");   
                desorganizar();
        }
    }//GEN-LAST:event_b11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaPuzzle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaPuzzle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaPuzzle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaPuzzle.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaPuzzle().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Mov;
    private javax.swing.JButton b1;
    private javax.swing.JButton b10;
    private javax.swing.JButton b11;
    private javax.swing.JButton b12;
    private javax.swing.JButton b13;
    private javax.swing.JButton b14;
    private javax.swing.JButton b15;
    private javax.swing.JButton b16;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JButton b6;
    private javax.swing.JButton b7;
    private javax.swing.JButton b8;
    private javax.swing.JButton b9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
